const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  getAppVersion:      ()           => ipcRenderer.invoke('get-app-version'),
  getBootTime:        ()           => ipcRenderer.invoke('get-boot-time'),
  getSystemInfo:      ()           => ipcRenderer.invoke('get-system-info'),
  isAdmin:            ()           => ipcRenderer.invoke('is-admin'),
  relaunchAdmin:      ()           => ipcRenderer.invoke('relaunch-admin'),
  getMetrics:         ()           => ipcRenderer.invoke('get-metrics'),
  minimize:           ()           => ipcRenderer.invoke('window-minimize'),
  maximize:           ()           => ipcRenderer.invoke('window-maximize'),
  close:              ()           => ipcRenderer.invoke('window-close'),
  loadSettings:       ()           => ipcRenderer.invoke('load-settings'),
  saveSettings:       (data)       => ipcRenderer.invoke('save-settings', data),
  listProfiles:       ()           => ipcRenderer.invoke('list-profiles'),
  saveProfile:        (data)       => ipcRenderer.invoke('save-profile', data),
  loadProfile:        (name)       => ipcRenderer.invoke('load-profile', name),
  deleteProfile:      (name)       => ipcRenderer.invoke('delete-profile', name),
  cloneProfile:       (name, newName) => ipcRenderer.invoke('clone-profile', { name, newName }),
  renameProfile:      (name, newName) => ipcRenderer.invoke('rename-profile', { name, newName }),
  exportProfile:      (name)       => ipcRenderer.invoke('export-profile', name),
  importProfile:      ()           => ipcRenderer.invoke('import-profile'),
  runTweak:           (id, action) => ipcRenderer.invoke('run-tweak', { id, action }),
  createRestorePoint: (desc)       => ipcRenderer.invoke('create-restore-point', desc),
  listRestorePoints:  ()           => ipcRenderer.invoke('list-restore-points'),
  restoreToPoint:     (seq)        => ipcRenderer.invoke('restore-to-point', seq),
  scanUwpApps:        ()           => ipcRenderer.invoke('scan-uwp-apps'),
  removeUwpApps:      (pkgs)       => ipcRenderer.invoke('remove-uwp-apps', pkgs),
  listInstalledWin32: ()           => ipcRenderer.invoke('list-installed-win32'),
  uninstallWin32Apps: (items)      => ipcRenderer.invoke('uninstall-win32-apps', items),
  getPrefetchAges:    ()           => ipcRenderer.invoke('get-prefetch-ages'),
  disableServices:    (svcs)       => ipcRenderer.invoke('disable-services', svcs),
  disableScheduledTasks: (tasks)   => ipcRenderer.invoke('disable-scheduled-tasks', tasks),
  getUnusedDevices:   ()           => ipcRenderer.invoke('get-unused-devices'),
  removeDevices:      (ids)        => ipcRenderer.invoke('remove-devices', ids),
  fivemClearCache:    (opts)       => ipcRenderer.invoke('fivem-clear-cache', opts),
  fivemCacheInfo:     ()           => ipcRenderer.invoke('fivem-cache-info'),
  fivemServerHealth:  ()           => ipcRenderer.invoke('fivem-server-health'),
  fivemIniBatch:      (changes)    => ipcRenderer.invoke('fivem-ini-batch', changes),
  fivemIniReadAll:    ()           => ipcRenderer.invoke('fivem-ini-read-all'),
  fivemIniWriteKey:   (opts)       => ipcRenderer.invoke('fivem-ini-write-key', opts),
  fivemScanMods:      ()           => ipcRenderer.invoke('fivem-scan-mods'),
  fivemReadSettings:  (manualPath) => ipcRenderer.invoke('fivem-read-settings', manualPath),
  fivemWriteSettings: (changes, manualPath) => ipcRenderer.invoke('fivem-write-settings', changes, manualPath),
  fivemReadLog:       ()           => ipcRenderer.invoke('fivem-read-log'),
  runAutoOpti:        (si)         => ipcRenderer.invoke('run-auto-opti', si),
  applyGameTweak:     (id, action, installPath) => ipcRenderer.invoke('apply-game-tweak', { gameId: id, action, installPath }),
  getProcesses:       ()           => ipcRenderer.invoke('get-processes'),
  killProcess:        (pid)        => ipcRenderer.invoke('kill-process', pid),
  gameBoostApply:     ()           => ipcRenderer.invoke('game-boost-apply'),
  gameBoostRestore:   ()           => ipcRenderer.invoke('game-boost-restore'),
  openPulseWindow:    ()           => ipcRenderer.invoke('open-pulse-window'),
  closePulseWindow:   ()           => ipcRenderer.invoke('close-pulse-window'),
  openFivemSettings:    ()           => ipcRenderer.invoke('open-fivem-settings'),
  closeFivemSettings:   ()           => ipcRenderer.invoke('close-fivem-settings'),
  openArmaSettings:     ()           => ipcRenderer.invoke('open-arma-settings'),
  closeArmaSettings:    ()           => ipcRenderer.invoke('close-arma-settings'),
  armaReadSettings:     (manualPath) => ipcRenderer.invoke('arma-read-settings', manualPath),
  armaWriteSettings:    (changes, manualPath) => ipcRenderer.invoke('arma-write-settings', changes, manualPath),
  analyticsPageVisit:   (page)       => ipcRenderer.invoke('analytics-page-visit', page),
  analyticsTweakApplied: ()          => ipcRenderer.invoke('analytics-tweak-applied'),
  pulseStart:         (opts)       => ipcRenderer.invoke('pulse-start', opts),
  pulseStop:          ()           => ipcRenderer.invoke('pulse-stop'),
  pulseFixMouse:      ()           => ipcRenderer.invoke('pulse-fix-mouse'),
  pulseGetPresets:    ()           => ipcRenderer.invoke('pulse-get-presets'),
  pulseDetectGame:    ()           => ipcRenderer.invoke('pulse-detect-game'),
  onPulseTick:        (cb)         => ipcRenderer.on('pulse-tick', (_, d) => cb(d)),
  getStartupItems:    ()           => ipcRenderer.invoke('get-startup-items'),
  toggleStartupItem:  (item)       => ipcRenderer.invoke('toggle-startup-item', item),
  getBootImpact:      ()           => ipcRenderer.invoke('get-boot-impact'),
  delayStartupItem:   (opts)       => ipcRenderer.invoke('delay-startup-item', opts),
  runPingTests:       ()           => ipcRenderer.invoke('run-ping-tests'),
  runPingTestsV2:     (opts)       => ipcRenderer.invoke('run-ping-tests-v2', opts),
  runNetHealth:       ()           => ipcRenderer.invoke('run-net-health'),
  benchmarkDns:       ()           => ipcRenderer.invoke('benchmark-dns'),
  detectGames:        ()           => ipcRenderer.invoke('detect-games'),
  startGameWatcher:   ()           => ipcRenderer.invoke('start-game-watcher'),
  stopGameWatcher:    ()           => ipcRenderer.invoke('stop-game-watcher'),
  getGameWatcherStatus: ()         => ipcRenderer.invoke('get-game-watcher-status'),
  getChangelog:       ()           => ipcRenderer.invoke('get-changelog'),
  addChangelogEntry:  (entry)      => ipcRenderer.invoke('add-changelog-entry', entry),
  clearChangelog:     ()           => ipcRenderer.invoke('clear-changelog'),
  scheduleTweak:      (opts)       => ipcRenderer.invoke('schedule-tweak', opts),
  listScheduledTweaks: ()          => ipcRenderer.invoke('list-scheduled-tweaks'),
  deleteScheduledTweak: (name)     => ipcRenderer.invoke('delete-scheduled-tweak', name),
  getTempSize:        ()           => ipcRenderer.invoke('get-temp-size'),
  getDiskUsage:       ()           => ipcRenderer.invoke('get-disk-usage'),
  getRecycleBinSize:  ()           => ipcRenderer.invoke('get-recycle-bin-size'),
  getCleanupSizes:    ()           => ipcRenderer.invoke('get-cleanup-sizes'),
  exportReport:       ()           => ipcRenderer.invoke('export-report'),
  cleanRam:           ()           => ipcRenderer.invoke('clean-ram'),
  getLatencySample:   ()           => ipcRenderer.invoke('get-latency-sample'),
  getHealthScore:     (settings)   => ipcRenderer.invoke('get-health-score', settings),
  runTweakHealth:     ()           => ipcRenderer.invoke('run-tweak-health'),
  detectAv:           ()           => ipcRenderer.invoke('detect-av'),
  checkUpdate:        ()           => ipcRenderer.invoke('check-update'),
  downloadUpdate:     ()           => ipcRenderer.invoke('download-update'),
  installUpdate:      ()           => ipcRenderer.invoke('install-update'),
  getWhatsNew:        (lang)       => ipcRenderer.invoke('get-whats-new', lang),
  runAppOptimizer:    (id, action) => ipcRenderer.invoke('run-app-optimizer', { id, action }),
  scanInstalledApps:      ()           => ipcRenderer.invoke('scan-installed-apps'),
  healthCheckAppOptimizer: ()          => ipcRenderer.invoke('health-check-app-optimizer'),
  onWindowsHealthProgress: (cb) => ipcRenderer.on('windows-health-progress', (_, d) => cb(d)),
  onPreflightProgress:     (cb) => ipcRenderer.on('preflight-progress',      (_, d) => cb(d)),
  onSpecProgress:     (cb) => ipcRenderer.on('spec-progress',     (_, d) => cb(d)),
  onLog:              (cb) => ipcRenderer.on('log',               (_, d) => cb(d)),
  onAutoOptiProgress: (cb) => ipcRenderer.on('auto-opti-progress',(_, d) => cb(d)),
  onDebloatProgress:  (cb) => ipcRenderer.on('debloat-progress',  (_, d) => cb(d)),
  onPingResult:       (cb) => ipcRenderer.on('ping-result',       (_, d) => cb(d)),
  onPingResultV2:     (cb) => ipcRenderer.on('ping-result-v2',    (_, d) => cb(d)),
  startLivePing:      (opts)       => ipcRenderer.invoke('start-live-ping', opts),
  stopLivePing:       ()           => ipcRenderer.invoke('stop-live-ping'),
  onLivePingTick:     (cb) => ipcRenderer.on('live-ping-tick',    (_, d) => cb(d)),
  onGameWatcherEvent: (cb) => ipcRenderer.on('game-watcher-event',(_, d) => cb(d)),
  onUpdateAvailable:  (cb) => ipcRenderer.on('update-available',  (_, d) => cb(d)),
  onUpdateProgress:   (cb) => ipcRenderer.on('update-progress',   (_, d) => cb(d)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', (_, d) => cb(d)),
  openExternal:       (url)        => ipcRenderer.invoke('open-external', url),
  openPath:           (p)          => ipcRenderer.invoke('open-path', p),
  setDiscordRpc:          (enabled)      => ipcRenderer.invoke('set-discord-rpc', enabled),
  setStartup:             (enabled)      => ipcRenderer.invoke('set-startup', enabled),
  discordSetPage:         (page)         => ipcRenderer.invoke('discord-set-page', page),
  discordSetTweaks:       (count)        => ipcRenderer.invoke('discord-set-tweaks', count),
  discordSetAppliedCount: (count)        => ipcRenderer.invoke('discord-set-applied-count', count),
  discordSetFiveM:        (has)          => ipcRenderer.invoke('discord-set-fivem', has),
  discordSetPulseGame:    (name)         => ipcRenderer.invoke('discord-set-pulse-game', name),
  discordSetActiveGame:   (name)         => ipcRenderer.invoke('discord-set-active-game', name),
  onDiscordReady:     (cb)         => ipcRenderer.on('discord-rpc-ready', () => cb()),
  submitBugReport:    (data)       => ipcRenderer.invoke('submit-bug-report', data),
  runFix:             (id)         => ipcRenderer.invoke('run-fix', id),
  runWindowsHealth:   ()           => ipcRenderer.invoke('run-windows-health'),
  runPreflightScan:   ()           => ipcRenderer.invoke('run-preflight-scan'),
  checkLghub:         ()           => ipcRenderer.invoke('check-lghub'),
  onTrayPulseChanged: (cb)         => ipcRenderer.on('tray-pulse-changed', (_, d) => cb(d)),
  getBiosInfo:        ()            => ipcRenderer.invoke('get-bios-info'),
  biosScewinRead:     ()            => ipcRenderer.invoke('bios-scewin-read'),
  biosScewinWrite:    (opts)        => ipcRenderer.invoke('bios-scewin-write', opts),
  biosHyperV:         (action)      => ipcRenderer.invoke('bios-hyper-v', { action }),
  biosCStates:        (action)      => ipcRenderer.invoke('bios-cstates', { action }),
  getRamInfo:         ()            => ipcRenderer.invoke('get-ram-info'),
  getRyzenAdjInfo:    ()            => ipcRenderer.invoke('ryzenadj-read'),
  applyRyzenAdj:      (opts)        => ipcRenderer.invoke('ryzenadj-apply', opts),
  getTemps:           ()            => ipcRenderer.invoke('get-temps'),
  fancontrolStart:    (minimized)   => ipcRenderer.invoke('fancontrol-start', minimized),
  fancontrolStop:     ()            => ipcRenderer.invoke('fancontrol-stop'),
  fancontrolStatus:   ()            => ipcRenderer.invoke('fancontrol-status'),
  cpuzReadTimings:    ()            => ipcRenderer.invoke('cpuz-read-timings'),
  getDriverInfo:      ()            => ipcRenderer.invoke('get-driver-info'),
  runBenchmark:       ()            => ipcRenderer.invoke('run-benchmark'),
  cleanPowerPlans:    ()            => ipcRenderer.invoke('clean-power-plans'),
  authStart:          ()            => ipcRenderer.invoke('auth-start'),
  authPoll:           (state)       => ipcRenderer.invoke('auth-poll', state),
  authVerify:         ()            => ipcRenderer.invoke('auth-verify'),
  authLogout:         ()            => ipcRenderer.invoke('auth-logout'),
  onAuthRequired:     (cb)          => ipcRenderer.on('auth-required', () => cb()),
  getPremiumUrl:      ()            => ipcRenderer.invoke('get-premium-url'),
  onTierUpdate:       (cb)          => ipcRenderer.on('tier-update', (_, d) => cb(d)),
  getMetricsHistory:  (opts)        => ipcRenderer.invoke('get-metrics-history', opts),
  ariaStart:          ()            => ipcRenderer.invoke('aria-start'),
  ariaStop:           ()            => ipcRenderer.invoke('aria-stop'),
  ariaBeforeTweak:    (opts)        => ipcRenderer.invoke('aria-before-tweak', opts),
  ariaAfterTweak:     (opts)        => ipcRenderer.invoke('aria-after-tweak', opts),
  getAriaInsights:    ()            => ipcRenderer.invoke('get-aria-insights'),
  onAriaTick:         (cb)          => ipcRenderer.on('aria-tick', (_, d) => cb(d)),
  startupTrace:       (msg)         => ipcRenderer.invoke('startup-trace', msg),
  adminDebugAppend:   (data)        => ipcRenderer.invoke('admin-debug-append', data),
  getSystemContext:   ()            => ipcRenderer.invoke('get-system-context'),
  buildRunPlan:       (opts)        => ipcRenderer.invoke('build-run-plan', opts),
  onGameDetected:     (cb)          => ipcRenderer.on('game-detected', (_, d) => cb(d)),
  onGameExited:       (cb)          => ipcRenderer.on('game-exited',   (_, d) => cb(d)),
  onFrameSession:     (cb)          => ipcRenderer.on('game-frame-session', (_, d) => cb(d)),
  onAriaSessionSummary: (cb)        => ipcRenderer.on('aria-session-summary', (_, d) => cb(d)),
  listGameBundles:      ()           => ipcRenderer.invoke('list-game-bundles'),
  saveGameBundle:       (bundle)     => ipcRenderer.invoke('save-game-bundle', bundle),
  deleteGameBundle:     (name)       => ipcRenderer.invoke('delete-game-bundle', name),
  loadGameBundle:       (name)       => ipcRenderer.invoke('load-game-bundle', name),
  onGameBundleActivated: (cb)        => ipcRenderer.on('game-bundle-activated', (_, d) => cb(d)),
  checkIsAdmin:         ()           => ipcRenderer.invoke('check-is-admin'),
  reboot:               ()            => ipcRenderer.invoke('reboot'),
  deleteRestorePoint:   (seq)        => ipcRenderer.invoke('delete-restore-point', seq),
  getSrDiskUsage:       ()           => ipcRenderer.invoke('get-sr-disk-usage'),
  saveTextFile:         (opts)       => ipcRenderer.invoke('save-text-file', opts),
  onAutoSnapshotDone:   (cb)         => ipcRenderer.on('auto-snapshot-done', (_, d) => cb(d)),
})
